@echo off
REM Weekly MYN audit -- push Scott Hoffman knowledge base to GitHub
REM Auto-generated by Monday audit task on April 27, 2026
set PATH=C:\Program Files\Git\cmd;%PATH%
cd /d "C:\Users\ram\Desktop\Command Center\myn-command-center"
git add scott-hoffman-knowledge-base.html
git commit -m "Weekly audit update 2026-04-27: longevity programming wedge, yoga TAM rebaseline ($138.66B), HR healthcare cost spike (+6-10%%)"
git push origin main
